config/routes.rb
MetaTrader::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :sessions => "users/sessions" }

  get "main_page", :to => "api_access#main_page", :as => "main_page"

  post "ping_session", :to => "api_access#ping_session", :as => "ping_session"

  post "tabs/common/submit", :to => "fixed_update#common_submit", :as => "common_submit"

  post "tabs/time/submit", :to => "fixed_update#time_submit", :as => "time_submit"

  post "tabs/backup/submit", :to => "fixed_update#backup_submit", :as => "backup_submit"

  post "tabs/symbol_group/submit", :to => "symbol#symbol_group_submit", :as => "symbol_group_submit"

  get "fetch_symbol", :to => "symbol#fetch_symbol", :as => "fetch_symbol"
  post "tabs/symbol/submit", :to => "symbol#symbol_submit", :as => "symbol_submit"
  get "new_symbol", :to => "symbol#new_symbol", :as => "new_symbol"

  get "fetch_group", :to => "group#fetch_group", :as => "fetch_group"
  post "tabs/group/submit", :to => "group#group_submit", :as => "group_submit"

  get "fetch_manager", :to => "manager#fetch_manager", :as => "fetch_manager"
  post "tabs/manager/submit", :to => "manager#manager_submit", :as => "manager_submit"

  get "fetch_feeder", :to => "feeder#fetch_feeder", :as => "fetch_feeder"
  post "tabs/feeder/submit", :to => "feeder#feeder_submit", :as => "feeder_submit"

  get "fetch_synchronization", :to => "synchronization#fetch_synchronization", :as => "fetch_synchronization"
  post "tabs/synchronization/submit", :to => "synchronization#synchronization_submit", :as => "synchronization_submit"

  get "fetch_plugin", :to => "plugin#fetch_plugin", :as => "fetch_plugin"
  post "tabs/plugin/submit", :to => "plugin#plugin_submit", :as => "plugin_submit"

  post "filter_account", :to => "account#filter_account", :as => "filter_account"
  get "fetch_account", :to => "account#fetch_account", :as => "fetch_account"
  post "tabs/account/submit", :to => "account#account_submit", :as => "account_submit"

  get "fetch_order", :to => "order#fetch_order", :as => "fetch_order"
  post "tabs/order/submit", :to => "order#order_submit", :as => "order_submit"

  post "tabs/access/submit", :to => "variable_update#access_submit", :as => "access_submit"
  delete "tabs/access/:position", :to => "variable_update#access_delete", :as => "delete_access_row"

  post "tabs/holiday/submit", :to => "variable_update#holiday_submit", :as => "holiday_submit"
  delete "tabs/holiday/:position", :to => "variable_update#holiday_delete", :as => "delete_holiday_row"

  post "tabs/data_server/submit", :to => "variable_update#data_server_submit", :as => "data_server_submit"
  delete "tabs/data_server/:position", :to => "variable_update#data_server_delete", :as => "delete_data_server_row"

  root :to => "api_access#main_page"

end

app/controllers/api_access_controller.rb
class ApiAccessController < ApplicationController
  include ApplicationHelper

  def main_page
    api = ApiMethods.new
    @common = api.getCommon(session)
    @access = api.getAccess(session)
    @data_server = api.getDataServer(session)
    @time = api.getTime(session)
    @holiday = api.getHoliday(session)
    @security = api.getSecurity(session)
    @symbol_group = api.getSymbolGroup(session)
    @symbol = api.getSymbol(session)
    @sym = api.symbolWithEmptySessions
    @backup = api.getBackup(session)
    @group = api.getGroup(session)
    @grp = {}
    @manager = api.getManager(session)
    @mgr = { "secgroups"=> {} }
    @feeder = api.getFeeder(session)
    @fdr = {}
    @synchronization = api.getSynchronization(session)
    @sync = {}
    @plugin = api.getPlugin(session)
    @plg = {"plugin" => {}, "params" => []}
    @account = api.getAccount(session)
    @act = {}
    @order = api.getOrder(session)
    @ord = { "conv_rates" => [] }
  end

  def ping_session
    api = ApiMethods.new
    api.ping(session)
    render :nothing => true
  end

end

app/views/api_access/main_page.html.erb
<% if can? :manage, :common %>
<%= render "fixed_update/common_form" %>
<% end %>

<% if can? :manage, :access %>
<%= render "variable_update/access_form" %>
<% end %>

<% if can? :manage, :data_server %>
<%= render "variable_update/data_server_form" %>
<% end %>

<% if can? :manage, :time %>
<%= render "fixed_update/time_form" %>
<% end %>

<% if can? :manage, :holiday %>
<%= render "variable_update/holiday_form" %>
<% end %>

<% if can? :manage, :symbol_group %>
<%= render "symbol/symbol_group_form" %>
<% end %>

<% if can? :manage, :symbols %>
<%= render "symbol/symbols_tab" %>
<% end %>

<% if can? :manage, :backup %>
<%= render "fixed_update/backup_form" %>
<% end %>

<% if can? :manage, :group %>
<div id="group-form-tab">
<%= render "group/group_tab" %>
</div>
<% end %>

<% if can? :manage, :manager %>
<%= render "manager/manager_tab" %>
<% end %>

<% if can? :manage, :feeder %>
<%= render "feeder/feeder_tab" %>
<% end %>

<% if can? :manage, :synchronization %>
<%= render "synchronization/synchronization_tab" %>
<% end %>

<% if can? :manage, :plugin %>
<div id="plugin-form-tab">
<%= render "plugin/plugin_tab" %>
</div>
<% end %>

<% if can? :manage, :account %>
<div id="account-form-tab">
<%= render "account/account_tab" %>
</div>
<% end %>

<% if can? :manage, :order %>
<div id="order-form-tab">
<%= render "order/order_tab" %>
</div>
<% end %>

<script>
  var ping_timer;
  var period = 150;

  $(document).ready(function(){
    ping_timer = setInterval(function () {
      $.ajax({
        method : "POST",
        url    : "<%= ping_session_path %>"
      });
    }, period * 1000);
  })
</script>