config/routes.rb
MetaTrader::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :sessions => "users/sessions" }

  get "main_page", :to => "api_access#main_page", :as => "main_page"

  post "ping_session", :to => "api_access#ping_session", :as => "ping_session"

  post "tabs/common/submit", :to => "fixed_update#common_submit", :as => "common_submit"

  post "tabs/time/submit", :to => "fixed_update#time_submit", :as => "time_submit"

  post "tabs/backup/submit", :to => "fixed_update#backup_submit", :as => "backup_submit"

  post "tabs/symbol_group/submit", :to => "symbol#symbol_group_submit", :as => "symbol_group_submit"

  get "fetch_symbol", :to => "symbol#fetch_symbol", :as => "fetch_symbol"
  post "tabs/symbol/submit", :to => "symbol#symbol_submit", :as => "symbol_submit"
  get "new_symbol", :to => "symbol#new_symbol", :as => "new_symbol"

  get "fetch_group", :to => "group#fetch_group", :as => "fetch_group"
  post "tabs/group/submit", :to => "group#group_submit", :as => "group_submit"

  get "fetch_manager", :to => "manager#fetch_manager", :as => "fetch_manager"
  post "tabs/manager/submit", :to => "manager#manager_submit", :as => "manager_submit"

  get "fetch_feeder", :to => "feeder#fetch_feeder", :as => "fetch_feeder"
  post "tabs/feeder/submit", :to => "feeder#feeder_submit", :as => "feeder_submit"

  get "fetch_synchronization", :to => "synchronization#fetch_synchronization", :as => "fetch_synchronization"
  post "tabs/synchronization/submit", :to => "synchronization#synchronization_submit", :as => "synchronization_submit"

  get "fetch_plugin", :to => "plugin#fetch_plugin", :as => "fetch_plugin"
  post "tabs/plugin/submit", :to => "plugin#plugin_submit", :as => "plugin_submit"

  post "filter_account", :to => "account#filter_account", :as => "filter_account"
  get "fetch_account", :to => "account#fetch_account", :as => "fetch_account"
  post "tabs/account/submit", :to => "account#account_submit", :as => "account_submit"

  get "fetch_order", :to => "order#fetch_order", :as => "fetch_order"
  post "tabs/order/submit", :to => "order#order_submit", :as => "order_submit"

  post "tabs/access/submit", :to => "variable_update#access_submit", :as => "access_submit"
  delete "tabs/access/:position", :to => "variable_update#access_delete", :as => "delete_access_row"

  post "tabs/holiday/submit", :to => "variable_update#holiday_submit", :as => "holiday_submit"
  delete "tabs/holiday/:position", :to => "variable_update#holiday_delete", :as => "delete_holiday_row"

  post "tabs/data_server/submit", :to => "variable_update#data_server_submit", :as => "data_server_submit"
  delete "tabs/data_server/:position", :to => "variable_update#data_server_delete", :as => "delete_data_server_row"

  root :to => "api_access#main_page"

end

app/controllers/symbol_controller.rb
class SymbolController < ApplicationController
  include ApplicationHelper

  def symbol_group_submit
    authorize! :update, :symbol_group
    data = params[:symbol_group_tab]
    api = ApiMethods.new
    begin
      data.each do |d|
        if d[1]["changed"] == "true"
          d[1].delete("changed")
          api.updateSymbolGroup(d[1],session)
        end
      end
      render :nothing => true
    rescue => e
      @error = "An error occured while executing this operation"
      render "shared/error"
    end
  end

  def symbol_submit
    authorize! :update, :symbol
    data = params[:symbol]
    new_sym = params[:new_symbol]
    if new_sym
      key = params[:symbol][:symbol]
    else
      key = params[:symbol_key]
    end
    api = ApiMethods.new
    @result = api.updateSymbol(key,data,session)
    @symbol_group = api.getSymbolGroup(session)
    @symbol = api.getSymbol(session)
    @sym = api.symbolWithEmptySessions
  end

  def new_symbol
    authorize! :create, :symbol
    api = ApiMethods.new
    @sym = api.symbolWithEmptySessions
    @symbol = api.getSymbol(session)
    @symbol_group = api.getSymbolGroup(session)
    render "fetch_symbol"
  end

  def fetch_symbol
    authorize! :read, :symbol
    pos = params[:pos]
    api = ApiMethods.new
    @symbol_group = api.getSymbolGroup(session)
    @symbol = api.getSymbol(session)
    @sym = @symbol[pos.to_i]
  end

end

app/views/symbol/_calculation_tab.html.erb
<div class="row-fluid">
  <div class="span12">
    Contract size: <%= text_field_tag "symbol[contract_size]", @sym["contract_size"], :style => "width:100px;" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span4">
    Initial margin: <%= text_field_tag "symbol[margin_initial]", @sym["margin_initial"], :style => "width:100px;" %>
  </div>
  <div class="span4">
    Maintenance: <%= text_field_tag "symbol[margin_maintenance]", @sym["margin_maintenance"], :style => "width:100px;" %>
  </div>
  <div class="span4">
    Hedged: <%= text_field_tag "symbol[margin_hedged]", @sym["margin_hedged"], :style => "width:100px;" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span4">
    Tick Size: <%= text_field_tag "symbol[tick_size]", @sym["tick_size"], :style => "width:100px;" %>
  </div>
  <div class="span4">
    Tick price: <%= text_field_tag "symbol[tick_value]", @sym["tick_value"], :style => "width:100px;" %></td>
  </div>
  <div class="span4">
    Percentage: <%= text_field_tag "symbol[margin_divider]",
    @sym["margin_divider"] ? number_with_precision((100/@sym["margin_divider"].to_f), :precision => 2) : "", :style => "width:100px;" %></td>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    Margin Calculation: <%= select_tag "symbol[margin_mode]", options_for_symbol_margin_mode(@sym["margin_mode"]), :style => "width:600px;" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    Profit Calculation: <%= select_tag "symbol[profit_mode]", options_for_symbol_profit_mode(@sym["profit_mode"]), :style => "width:600px;" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
     <%= hidden_field_tag "symbol[margin_hedged_strong]", '0' %>
     <%= check_box_tag "symbol[margin_hedged_strong]", '1', @sym["margin_hedged_strong"]==1 %> Strong hedged margin mode
  </div>
</div>

app/views/symbol/_filtration_tab.html.erb
<div class="row-fluid">
  <div class="span12">
     <%= hidden_field_tag "symbol[realtime]", '0' %>
     <%= check_box_tag "symbol[realtime]", '1', @sym["realtime"]==1 %> Allow real-time quotes from datafeeds
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    <%= hidden_field_tag "symbol[logging]", '0' %>
    <%= check_box_tag "symbol[logging]", '1', @sym["logging"]==1 %> Save all incoming prices in a file(this will slow down your server)
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    Filtration Level: <%= text_field_tag "symbol[filter]", @sym["filter"], :style => "width:60px;" %> points (must not be less than 4 or 5 times spread by default)
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    Automatic limit: <%= select_tag "symbol[filter_limit]", options_for_symbol_filter_limit(@sym["filter_limit"]), :style => "width:71px;" %> % of the current market price
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    Filter: <%= select_tag "symbol[filter_counter]", options_for_symbol_filter_counter(@sym["filter_counter"]), :style => "width:71px;" %> wrong quotes coming one after another
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    Ignore quotes: <%= text_field_tag "symbol[quotes_delay]", @sym["quotes_delay"], :style => "width:60px;" %> seconds after session starts
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    Smoothing: <%= select_tag "symbol[filter_smoothing]", options_for_symbol_filter_smoothing(@sym["filter_smoothing"]), :style => "width:71px;" %> ticks
  </div>
</div>

app/views/symbol/_sessions_tab.html.erb
<table>
  <tr>
    <th>Day</th>
    <th colspan=3>Quotes</th>
    <th colspan=3>Trade</th>
  </tr>
<% @sym["sessions"].each_with_index do |session, ix| %>
  <tr>
    <td><%= Date::DAYNAMES[ix] %></td>
    <% session["quote"].each_with_index do |quote, qix| %>
      <td>
      <%=text_field_tag "symbol[sessions][#{ix}][quote][#{qix}][open_hour]","%02d"%quote["open_hour"],:style=>"width:17px;"%>:<%=text_field_tag "symbol[sessions][#{ix}][quote][#{qix}][open_min]","%02d"%quote["open_min"],:style=>"width:17px;"%>
      -
      <%=text_field_tag "symbol[sessions][#{ix}][quote][#{qix}][close_hour]","%02d"%quote["close_hour"],:style=>"width:17px;"%>:<%=text_field_tag "symbol[sessions][#{ix}][quote][#{qix}][close_min]","%02d"%quote["close_min"],:style=>"width:17px;"%>
      </td>
    <% end %>
    <% session["trade"].each_with_index do |trade, tix| %>
      <td>
      <%=text_field_tag "symbol[sessions][#{ix}][trade][#{tix}][open_hour]","%02d"%trade["open_hour"],:style=>"width:17px;"%>:<%=text_field_tag "symbol[sessions][#{ix}][trade][#{tix}][open_min]","%02d"%trade["open_min"],:style=>"width:17px;"%>
      -
      <%=text_field_tag "symbol[sessions][#{ix}][trade][#{tix}][close_hour]","%02d"%trade["close_hour"],:style=>"width:17px;"%>:<%=text_field_tag "symbol[sessions][#{ix}][trade][#{tix}][close_min]","%02d"%trade["close_min"],:style=>"width:17px;"%>
      </td>
    <% end %>
  </tr>
<% end if @sym["sessions"] %>
</table>

app/views/symbol/_swaps_tab.html.erb
<div class="row-fluid">
  <div class="span12">
     <%= hidden_field_tag "symbol[swap_enable]", '0' %>
     <%= check_box_tag "symbol[swap_enable]", '1', @sym["swap_enable"]==1 %> Enable
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    Type: <%= select_tag "symbol[swap_type]", options_for_symbol_swap_type(@sym["swap_type"]), :style => "width:400px;" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    Long positions: <%= text_field_tag "symbol[swap_long]", @sym["swap_long"], :style => "width:100px;" %>
  </div>
  <div class="span6">
    Short positions: <%= text_field_tag "symbol[swap_short]", @sym["swap_short"], :style => "width:100px;" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    3-day swaps: <%= select_tag "symbol[swap_rollover3days]", options_for_symbol_swap_rollover3days(@sym["swap_rollover3days"]) %>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
     <%= hidden_field_tag "symbol[swap_openprice]", '0' %>
     <%= check_box_tag "symbol[swap_openprice]", '1', @sym["swap_openprice"]==1 %> Use open price for position value calculation
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
     <%= hidden_field_tag "find_this", '0' %>
     <%= check_box_tag "find_this", '1', @sym["find_this"]==1 %> Charge variation margin on rollover (FIND THIS)
  </div>
</div>

app/views/symbol/_symbol_form.html.erb
<%= form_tag symbol_submit_path, :method => "POST", :remote => true do %>
  <%= hidden_field_tag "new_symbol", @sym.empty? %>
  <%= hidden_field_tag "symbol_key", @sym["symbol"] %>
  <%= tabbed_panel do |tp| %>
    <% tp.add_tab("Symbol") do %>
      <%= render "symbol/symbol_tab" %>
    <% end %>
    <% tp.add_tab("Filtration") do %>
      <%= render "symbol/filtration_tab" %>
    <% end %>
    <% tp.add_tab("Calculation") do %>
      <%= render "symbol/calculation_tab" %>
    <% end %>
    <% tp.add_tab("Swaps") do %>
      <%= render "symbol/swaps_tab" %>
    <% end %>
    <% tp.add_tab("Sessions") do %>
      <%= render "symbol/sessions_tab" %>
    <% end %>
    <%= submit_tag %>
  <% end %>
<% end %>

app/views/symbol/_symbol_group_form.html.erb
<% unless @symbol_group.nil? %>
  <%= form_tag symbol_group_submit_path, :method => "POST", :remote => true, :class => "symbol_group_form" do %>
    <%= submit_tag %>
    <table>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th style="width: 600px;">Symbols</th>
      </tr>
      <% @symbol_group.each_with_index do |sg, ix| %>
        <tr>
          <td>
            <%= hidden_field_tag "symbol_group_tab[#{ix}][position]", ix %>
            <%= hidden_field_tag "symbol_group_tab[#{ix}][changed]", false, :class => "symbol_group_changed" %>
            <%= text_field_tag "symbol_group_tab[#{ix}][name]", sg["name"], :class => "symbol_group_field" %>
          </td>
          <td>
            <%= text_field_tag "symbol_group_tab[#{ix}][description]", sg["description"], :class => "symbol_group_field"%>
          </td>
          <td>
            <%= text_field_tag "symbol_group_symbols", get_symbol_group_symbols(ix, @symbol), :disabled => true, :style => "width: 99%;" %>
          </td>
        </tr>
      <% end %>
    </table>
  <% end %>
<% end %>

app/views/symbol/_symbol_tab.html.erb
<div class="row-fluid">
  <div class="span4">
    Symbol: <%= text_field_tag "symbol[symbol]", @sym["symbol"], :style => "width: 120px" %>
  </div>
  <div class="span4">
    Source: <%= select_tag "symbol[source]", options_for_source_select(@symbol, @sym["source"]), :style => "width: 100px" %>
  </div>
  <div class="span4">
    Digits: <%= select_tag "symbol[digits]", options_for_symbol_digits(@sym["digits"]), :style => "width: 50px" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    Description: <%= text_field_tag "symbol[description]", @sym["description"], :style => "width: 300px" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span4">
    Type: <%= select_tag "symbol[type]", options_for_symbol_type(@symbol_group, @sym["type"]), :style => "width: 100px" %>
  </div>
  <div class="span4">
    Execution: <%= select_tag "symbol[exemode]", options_for_symbol_execution(@sym["exemode"]), :style => "width: 100px" %>
  </div>
  <div class="span4">
    Currency: <%= select_tag "symbol[currency]", options_for_symbol_currency(@sym["currency"]), :disabled =>true, :style => "width: 80px" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span4">
    Trade: <%= select_tag "symbol[trade]", options_for_symbol_trade(@sym["trade"]), :style => "width: 120px" %>
  </div>
  <div class="span4">
    <%#Background: <%= text_field_tag "symbol[background_color]", @sym["background_color"], :style => "width: 100px" %>
  </div>
  <div class="span4">
    Margin Currency: <%= select_tag "symbol[margin_currency]", options_for_symbol_currency(@sym["margin_currency"]), :style => "width: 80px" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    Maximum lots for IE: <%= text_field_tag "symbol[instant_max_volume]", @sym["instant_max_volume"] ? @sym["instant_max_volume"]/100 : "", :style => "width: 50px" %>
  </div>
  <div class="span6">
    Orders: <%= select_tag "symbol[gtc_pendings]", options_for_symbol_orders(@sym["gtc_pendings"]), :style => "width: 240px" %>
  </div>
</div>
<div class="row-fluid">
  <div class="span4">
    Spread by default: <%= text_field_tag "symbol[spread]", @sym["spread"], :style => "width: 40px" %> pt
  </div>
  <div class="span4">
    <%= hidden_field_tag "symbol[long_only]", '0' %>
    Long only: <%= check_box_tag "symbol[long_only]", '1', @sym["long_only"]==1 %>
  </div>
  <div class="span4">
    Limit & stop level: <%= text_field_tag "symbol[stops_level]", @sym["stops_level"], :style => "width: 40px" %> pt
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    Spread balance: <%= select_tag "symbol[spread_balance]", options_for_spread_balance(@sym), :style => "width: 180px"  %>
  </div>
  <div class="span6">
    Freeze level: <%= text_field_tag "symbol[freeze_level]", @sym["freeze_level"], :style => "width: 40px"  %> pt
  </div>
</div>

app/views/symbol/_symbols_tab.html.erb
<div id="symbols-form-tab">
<% unless @symbol.nil? %>
<div class="row-fluid">
  <div class="span4">
    <a href="#" id="new-symbol-link">New symbol</a>
    <table>
      <tr>
        <th>Symbol</th>
        <th>Type</th>
        <th>Execution</th>
        <th>Filter</th>
        <th>Spread</th>
        <th>Stops</th>
        <th>Long</th>
        <th>Short</th>
        <th>Digits</th>
        <th>Trade</th>
      </tr>
      <% @symbol.each_with_index do |symbol, ix|%>
        <tr class="symbol-row" data-pos="<%= ix %>">
          <td><%= symbol["symbol"] %></td>
          <td><%= @symbol_group[symbol["type"]]["name"] %></td>
          <td>
            <%= case symbol["exemode"] ; when 0 ; "Request" ; when 1 ; "Instant" ; when 2 ; "Market" ; end %>
          </td>
          <td><%= symbol["filter"]==0 ? "No" : symbol["filter"] %></td>
          <td><%= symbol["spread"] %></td>
          <td><%= symbol["stops_level"] %></td>
          <td><%= symbol["swap_long"] %></td>
          <td><%= symbol["swap_short"] %></td>
          <td><%= symbol["digits"] %></td>
          <td>
            <%= case symbol["trade"] ; when 0 ; "No" ; when 1 ; "Close" ; when 2 ; "Full" ; end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div id="symbol-form" class="span8">
    <%= render "symbol/symbol_form" %>
  </div>
</div>

<div class="row-fluid">
  <div class="span6">
    {"ask_tickvalue"=>0, "bid_tickvalue"=>0, "count"=>32, "count_original"=>0, "expiration"=>0, 
    "filter_reserved"=>0, "multiply"=>100000, "point"=>1.0e-05, "profit_reserved"=>0, "starting"=>0, value_date"=>0}
  </div>
  <div class="span6">
          "sessions"=>[

        {"quote"=>[{"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                   {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                   {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}],
        "quote_overnight"=>-1,
        "trade"=>[{"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                  {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                  {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}],
        "trade_overnight"=>-1},

        {"quote"=>[{"close"=>1440, "close_hour"=>24, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                   {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                   {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}],
        "quote_overnight"=>-1,
        "trade"=>[{"close"=>1440, "close_hour"=>24, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                  {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                  {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}],
        "trade_overnight"=>-1},
        {"quote"=>[{"close"=>1440, "close_hour"=>24, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                   {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                   {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}],
        "quote_overnight"=>-1,
        "trade"=>[{"close"=>1440, "close_hour"=>24, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                  {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                  {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}],
        "trade_overnight"=>-1},
        {"quote"=>[{"close"=>1440, "close_hour"=>24, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                   {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                   {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}], 
        "quote_overnight"=>-1,
        "trade"=>[{"close"=>1440, "close_hour"=>24, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                  {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0},
                  {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}],
        "trade_overnight"=>-1},
        {"quote"=>[{"close"=>1440, "close_hour"=>24, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}, {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}, {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}], "quote_overnight"=>-1, "trade"=>[{"close"=>1440, "close_hour"=>24, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}, {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}, {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}], "trade_overnight"=>-1}, {"quote"=>[{"close"=>1380, "close_hour"=>23, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}, {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}, {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}], "quote_overnight"=>-1, "trade"=>[{"close"=>1380, "close_hour"=>23, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}, {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}, {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}], "trade_overnight"=>-1}, {"quote"=>[{"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}, {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}, {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}], "quote_overnight"=>-1, "trade"=>[{"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}, {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}, {"close"=>0, "close_hour"=>0, "close_min"=>0, "open"=>0, "open_hour"=>0, "open_min"=>0}], "trade_overnight"=>-1}]
    </div>
  </div>
<% end %>
</div>

app/views/symbol/fetch_symbol.js.erb
$("#symbol-form").html("<%= escape_javascript(render 'symbol/symbol_form') %>")
$('.tabbed_panel .tab a').click(function(event){ event.preventDefault(); handle_tab_click($(this))});     
$.Jookie.Initialise("tab_memory", 60*24*365);
$('.tabbed_panel').each(function(){ pre_select_tab($(this))});

/*
$("#symbol_symbol").val("<%= @sym['symbol'] %>");
$("#symbol_source").val("<%= @sym['symbol'] %>");
$("#symbol_digits").val("<%= @sym['symbol'] %>");
$("#symbol_description").val("<%= @sym['symbol'] %>");
$("#symbol_type").val("<%= @sym['symbol'] %>");
$("#symbol_exemode").val("<%= @sym['symbol'] %>");
$("#symbol_currency").val("<%= @sym['symbol'] %>");
$("#symbol_trade").val("<%= @sym['symbol'] %>");
$("#symbol_background_color").val("<%= @sym['symbol'] %>");
$("#symbol_margin_currency").val("<%= @sym['symbol'] %>");
$("#symbol_instant_max_volume").val("<%= @sym['symbol'] %>");
$("#symbol_gtc_pendings").val("<%= @sym['symbol'] %>");
$("#symbol_spread").val("<%= @sym['symbol'] %>");
$("#symbol_long_only").val("<%= @sym['symbol'] %>");
$("#symbol_long_only").val("<%= @sym['symbol'] %>");
$("#symbol_stops_level").val("<%= @sym['symbol'] %>");
$("#symbol_spread_balance").val("<%= @sym['symbol'] %>");
$("#symbol_freeze_level").val("<%= @sym['symbol'] %>");
*/

app/views/symbol/symbol_submit.js.erb
$("#symbols-form-tab").html("<%= escape_javascript(render 'symbol/symbols_tab') %>")
$('.tabbed_panel .tab a').click(function(event){ event.preventDefault(); handle_tab_click($(this))});     
$.Jookie.Initialise("tab_memory", 60*24*365);
$('.tabbed_panel').each(function(){ pre_select_tab($(this))});
initSymbolEvents();