config/routes.rb
MetaTrader::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :sessions => "users/sessions" }

  get "main_page", :to => "api_access#main_page", :as => "main_page"

  post "ping_session", :to => "api_access#ping_session", :as => "ping_session"

  post "tabs/common/submit", :to => "fixed_update#common_submit", :as => "common_submit"

  post "tabs/time/submit", :to => "fixed_update#time_submit", :as => "time_submit"

  post "tabs/backup/submit", :to => "fixed_update#backup_submit", :as => "backup_submit"

  post "tabs/symbol_group/submit", :to => "symbol#symbol_group_submit", :as => "symbol_group_submit"

  get "fetch_symbol", :to => "symbol#fetch_symbol", :as => "fetch_symbol"
  post "tabs/symbol/submit", :to => "symbol#symbol_submit", :as => "symbol_submit"
  get "new_symbol", :to => "symbol#new_symbol", :as => "new_symbol"

  get "fetch_group", :to => "group#fetch_group", :as => "fetch_group"
  post "tabs/group/submit", :to => "group#group_submit", :as => "group_submit"

  get "fetch_manager", :to => "manager#fetch_manager", :as => "fetch_manager"
  post "tabs/manager/submit", :to => "manager#manager_submit", :as => "manager_submit"

  get "fetch_feeder", :to => "feeder#fetch_feeder", :as => "fetch_feeder"
  post "tabs/feeder/submit", :to => "feeder#feeder_submit", :as => "feeder_submit"

  get "fetch_synchronization", :to => "synchronization#fetch_synchronization", :as => "fetch_synchronization"
  post "tabs/synchronization/submit", :to => "synchronization#synchronization_submit", :as => "synchronization_submit"

  get "fetch_plugin", :to => "plugin#fetch_plugin", :as => "fetch_plugin"
  post "tabs/plugin/submit", :to => "plugin#plugin_submit", :as => "plugin_submit"

  post "filter_account", :to => "account#filter_account", :as => "filter_account"
  get "fetch_account", :to => "account#fetch_account", :as => "fetch_account"
  post "tabs/account/submit", :to => "account#account_submit", :as => "account_submit"

  get "fetch_order", :to => "order#fetch_order", :as => "fetch_order"
  post "tabs/order/submit", :to => "order#order_submit", :as => "order_submit"

  post "tabs/access/submit", :to => "variable_update#access_submit", :as => "access_submit"
  delete "tabs/access/:position", :to => "variable_update#access_delete", :as => "delete_access_row"

  post "tabs/holiday/submit", :to => "variable_update#holiday_submit", :as => "holiday_submit"
  delete "tabs/holiday/:position", :to => "variable_update#holiday_delete", :as => "delete_holiday_row"

  post "tabs/data_server/submit", :to => "variable_update#data_server_submit", :as => "data_server_submit"
  delete "tabs/data_server/:position", :to => "variable_update#data_server_delete", :as => "delete_data_server_row"

  root :to => "api_access#main_page"

end

app/controllers/variable_update_controller.rb
class VariableUpdateController < ApplicationController
  include ApplicationHelper

  def access_submit
    authorize! :update, :access
    @data = params[:access_tab]
    @new = params[:access_new_record] == "true"
    api = ApiMethods.new
    begin
      @result = api.updateAccess(@data,session)
    rescue => e
      @error = true
    end
  end

  def access_delete
    authorize! :delete, :access
    @position = params[:position]
    api = ApiMethods.new
    @result = api.deleteAccess(@position,session)
  end

  def data_server_submit
    authorize! :update, :data_server
    data = params[:data_server_tab]
    @new = params[:data_server_new_record] == "true"
    api = ApiMethods.new
    begin
      @result = api.updateDataServer(data,session)
      position = data["position"]
      @data = api.getDataServer(session,position)
      @data["position"] = position
    rescue => e
      @error = true
    end
  end

  def data_server_delete
    authorize! :delete, :data_server
    @position = params[:position]
    api = ApiMethods.new
    @result = api.deleteDataServer(@position,session)
  end

  def holiday_submit
    authorize! :update, :holiday
    @data = params[:holiday_tab]
    @new = params[:holiday_new_record] == "true"
    api = ApiMethods.new
    begin
      @result = api.updateHoliday(@data,session)
    rescue => e
      @error = true
    end
  end

  def holiday_delete
    authorize! :delete, :holiday
    @position = params[:position]
    api = ApiMethods.new
    @result = api.deleteHoliday(@position,session)
  end

end

app/views/variable_update/_access_form.html.erb
<% unless @access.nil? %>
  <table class="access_table" style="margin: 10px">
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Comment</th>
      <th>Delete</th>
    </tr>
    <% @access.each_with_index do |row, ix| %>
      <tr class="access_row" data-position="<%= ix %>" data-action="<%= row["action"] %>" data-from="<%= ApiMethods.long2ip(row["from"]) %>" data-to="<%= ApiMethods.long2ip(row["to"]) %>" data-comment="<%= row["comment"] %>">
        <td class="el"><%= ApiMethods.long2ip(row["from"]) %></td>
        <td class="el"><%= ApiMethods.long2ip(row["to"]) %></td>
        <td class="el"><%= row["comment"] %></td>
        <td><%= link_to "delete", delete_access_row_path(:position => ix), :remote=> true, :method => :delete %></td>
      </tr>
    <% end %>
  </table>
  <%= form_tag access_submit_path, :method => "POST", :remote => true do %>
    <%= hidden_field_tag "access_new_record", true %>
    <%= hidden_field_tag "access_tab[position]", @access.count %>
    <label for="access_tab[action]">Action: </label>
    <%= select_tag "access_tab[action]", options_for_access_action %>
    <br/>
    <label for="access_tab[from]">From: </label>
    <%= text_field_tag "access_tab[from]" %>
    <label for="access_tab[to]">to: </label>
    <%= text_field_tag "access_tab[to]" %>
    <br/>
    <label for="access_tab[comment]">Comment: </label>
    <%= text_field_tag "access_tab[comment]" %>
    <br/>
    <%= submit_tag %>
    <%= link_to "new", "#", :id => "new_access" %>
  <% end %>
<% end %>

app/views/variable_update/_data_server_form.html.erb
<% unless @data_server.nil? %>
  <table class="data_server_table" style="margin: 10px">
    <tr>
      <th>Server</th>
      <th>Description</th>
      <th>Internal IP Address</th>
      <th>Priority</th>
      <th>Loading</th>
      <th>Delete</th>
    </tr>
    <% @data_server.each_with_index do |row, ix| %>
      <tr class="data_server_row" data-position="<%= ix %>" data-description="<%= row["description"] %>"
        data-ip="<%= ApiMethods.long2ip(row["ip"]) %>" data-ipinternal="<%= ApiMethods.long2ip(row["ip_internal"]) %>" data-priority="<%= row["priority"] %>" data-server="<%= row["server"] %>">
        <td class="el"><%= row["server"] %></td>
        <td class="el"><%= row["description"] %></td>
        <td class="el"><%= ApiMethods.long2ip(row["ip_internal"]) %></td>
        <td class="el"><%= row["priority"] == 255 ? "Idle" : row["priority"] %></td>
        <td class="el"><%= row["loading"] == 4294967295 ? "n/a" : row["loading"] %></td>
        <td><%= link_to "delete", delete_data_server_row_path(:position => ix), :remote=> true, :method => :delete %></td>
      </tr>
    <% end %>
  </table>
  <%= form_tag data_server_submit_path, :method => "POST", :remote => true do %>
    <%= hidden_field_tag "data_server_new_record", true %>
    <%= hidden_field_tag "data_server_tab[position]", @data_server.count %>
    <label for="data_server_tab[description]">Description: </label>
    <%= text_field_tag "data_server_tab[description]" %>
    <br/>
    <label for="data_server_tab[server]">Public server address: </label>
    <%= text_field_tag "data_server_tab[server]" %>
    <label for="data_server_tab[ip_internal]">Internal IP Address: </label>
    <%= text_field_tag "data_server_tab[ip_internal]" %>
    <br/>
    <label for="data_server_tab[priority]">Priority: </label>
    <%= select_tag "data_server_tab[priority]", options_for_data_server_priority %>
    <br/>
    <%= submit_tag %>
    <%= link_to "new", "#", :id => "new_data_server" %>
  <% end %>
<% end %>

app/views/variable_update/_holiday_form.html.erb
<% unless @holiday.nil? %>
  <table class="holiday_table" style="margin: 10px">
    <tr>
      <th>Day</th>
      <th>From</th>
      <th>To</th>
      <th>Securities</th>
      <th>Description</th>
      <th>Delete</th>
    </tr>
    <% @holiday.each_with_index do |row, ix| %>
      <tr class="holiday_row" data-position="<%= ix %>" data-day="<%= row["day"] %>" data-month="<%= row["month"] %>" data-year="<%= row["year"] %>" data-from="<%= row["from"] %>" data-to="<%= row["to"] %>"  data-symbol="<%= row["symbol"] %>" data-description="<%= row["description"] %>" data-enable="<%= row["enable"] %>">
        <td class="el"><%= row["year"]==0 ? "****" : row["year"] %>.<%= row["month"].to_s.rjust(2, '0') %>.<%= row["day"].to_s.rjust(2, '0') %></td>
        <td class="el"><%= "#{(row['from']/60).to_i.to_s.rjust(2, '0')}:#{(row['from'].to_i-(row['from']/60).to_i*60).to_s.rjust(2, '0')}" %></td>
        <td class="el"><%= "#{(row['to']/60).to_i.to_s.rjust(2, '0')}:#{(row['to'].to_i-(row['to']/60).to_i*60).to_s.rjust(2, '0')}" %></td>
        <td class="el"><%= row["symbol"] %></td>
        <td class="el"><%= row["description"] %></td>
        <td><%= link_to "delete", delete_holiday_row_path(:position => ix), :remote=> true, :method => :delete %></td>
      </tr>
    <% end %>
  </table>
  <%= form_tag holiday_submit_path, :method => "POST", :remote => true do %>
    <%= hidden_field_tag "holiday_new_record", true %>
    <%= hidden_field_tag "holiday_tab[position]", @holiday.count %>
    <label for="holiday_tab[enable]">Enable: </label>
    <%= hidden_field_tag "holiday_tab[enable]", '0' %>
    <%= check_box_tag "holiday_tab[enable]", '1', true %>
    <br/>
    <label>Date: </label>
    <%= number_field_tag "holiday_tab[year]" %>.<%= number_field_tag "holiday_tab[month]" %>.<%= number_field_tag "holiday_tab[day]" %>
    <%= check_box_tag "holiday_tab_yearly_check" %>Every year
    <br/>
    <label for="holiday_tab[from]">From: </label>
    <%= number_field_tag "holiday_tab[from][hour]" %>:<%= number_field_tag "holiday_tab[from][minute]" %>
    <label for="holiday_tab[to]">to: </label>
    <%= number_field_tag "holiday_tab[to][hour]" %>:<%= number_field_tag "holiday_tab[to][minute]" %>
    <br/>
    <label for="holiday_tab[symbol]">Symbol: </label>
    <%= select_tag "holiday_tab[symbol]", options_for_holiday_securities(@security) %>
    <br/>
    <label for="holiday_tab[description]">Description: </label>
    <%= text_field_tag "holiday_tab[description]"%>
    <br/>
    <%= submit_tag %>
    <%= link_to "new", "#", :id => "new_holiday" %>
  <% end %>
<% end %>

app/views/variable_update/access_delete.js.erb
$("#access_new_record").val("true");
<% if @result[:success] %>
  $(".access_table .access_row[data-position='<%= @position%>']").first().remove();
  $(".access_table .access_row").each(function(ix,el){
    if( parseInt($(el).attr("data-position")) > <%= @position %> ){
      $(el).attr("data-position", parseInt($(el).attr("data-position")) - 1);
      $(el).find("td a").first().attr("href", "/tabs/access/"+$(el).attr("data-position").toString());
    }
  });
<% elsif !@result[:success] %>
  alert("<%= @result[:msg] %>");
<% end %>

app/views/variable_update/access_submit.js.erb
<% if @error %>
alert("An error occured while executing this operation");
<% elsif @new && @result[:success] %>
  $("#access_new_record").val("true");
  $(".access_table").append('<tr class="access_row" data-position="<%= @data["position"] %>" data-action="<%= @data["action"] %>" data-from="<%= @data["from"] %>" data-to="<%= @data["to"] %>" data-comment="<%= @data["comment"] %>"><td><%= @data["from"] %></td><td><%= @data["to"] %></td><td><%= @data["comment"] %></td><td><%= link_to "delete", delete_access_row_path(:position => @data["position"]), :remote=> true, :method => :delete %></td></tr>');
  $("#access_tab_position").val('<%= @data["position"].to_i + 1 %>');
  $("#access_tab_action").val("");
  $("#access_tab_from").val("");
  $("#access_tab_to").val("");
  $("#access_tab_comment").val("");
<% elsif @result[:success] %>
  $("#access_new_record").val("true");
  var row = $(".access_row[data-position='<%= @data['position']%>']")[0];
  $(row).attr("data-action", "<%= @data['action'] %>");
  $(row).attr("data-from", "<%= @data['from'] %>");
  $(row).attr("data-to", "<%= @data['to'] %>");
  $(row).attr("data-comment", "<%= @data['comment'] %>");
  $($(row).find("td")[0]).text("<%= @data['from'] %>");
  $($(row).find("td")[1]).text("<%= @data['to'] %>");
  $($(row).find("td")[2]).text("<%= @data['comment'] %>");
  var last_position = $(".access_table").find("tr").last().attr("data-position");
  $("#access_tab_position").val(last_position + 1);
  $("#access_tab_action").val("");
  $("#access_tab_from").val("");
  $("#access_tab_to").val("");
  $("#access_tab_comment").val("");
<% elsif !@result[:success] %>
  alert("<%= @result[:msg] %>");
<% end %>

app/views/variable_update/data_server_delete.js.erb
$("#data_server_new_record").val("true");
<% if @result[:success] %>
  $(".data_server_table .data_server_row[data-position='<%= @position%>']").first().remove();
  $(".data_server_table .data_server_row").each(function(ix,el){
    if( parseInt($(el).attr("data-position")) > <%= @position %> ){
      $(el).attr("data-position", parseInt($(el).attr("data-position")) - 1);
      $(el).find("td a").first().attr("href", "/tabs/data_server/"+$(el).attr("data-position").toString());
    }
  });
<% elsif !@result[:success] %>
  alert("<%= @result[:msg] %>");
<% end %>

app/views/variable_update/data_server_submit.js.erb
<% if @error %>
alert("An error occured while executing this operation");
<% elsif @new && @result[:success] %>
  $("#data_server_new_record").val("true");
  $(".data_server_table").append('<tr class="data_server_row" data-position="<%= @data["position"] %>" data-description="<%= @data["description"] %>" data-ip="<%= ApiMethods.long2ip(@data["ip"]) %>" data-ipinternal="<%= ApiMethods.long2ip(@data["ip_internal"]) %>" data-priority="<%= @data["priority"] %>"  data-server="<%= @data["server"] %>"><td class="el"><%= @data["server"] %></td><td class="el"><%= @data["description"] %></td><td class="el"><%= ApiMethods.long2ip(@data["ip_internal"]) %></td><td class="el"><%= @data["priority"] == 255 ? "Idle" : @data["priority"] %></td><td class="el"><%= @data["loading"] == 4294967295 ? "n/a" : @data["loading"] %></td><td><%= link_to "delete", delete_data_server_row_path(:position => @data["position"]), :remote=> true, :method => :delete %></td></tr>');
  $("#data_server_tab_position").val('<%= @data["position"].to_i + 1 %>');
  $("#data_server_tab_description").val("");
  $("#data_server_tab_server").val("");
  $("#data_server_tab_ip_internal").val("");
  $("#data_server_tab_priority").val("");
<% elsif @result[:success] %>
  $("#data_server_new_record").val("true");
  var row = $(".data_server_row[data-position='<%= @data['position']%>']")[0];
  $(row).attr("data-description", "<%= @data['description'] %>");
  $(row).attr("data-ip", "<%= @data['ip'] %>");
  $(row).attr("data-server", "<%= @data['server'] %>");
  $(row).attr("data-ipinternal", "<%= @data['ip_internal'] %>");
  $(row).attr("data-priority", "<%= @data['priority'] %>");
  $($(row).find("td")[0]).text("<%= @data['server'] %>");
  $($(row).find("td")[1]).text("<%= @data['description'] %>");
  $($(row).find("td")[2]).text("<%= ApiMethods.long2ip(@data['ip_internal']) %>");
  $($(row).find("td")[3]).text("<%= @data['priority'] == 255 ? 'Idle' : @data['priority'] %>");
  $($(row).find("td")[4]).text("<%= @data['loading'] == 4294967295 ? 'n/a' : @data['loading'] %>");
  var last_position = $(".data_server_table").find("tr").last().attr("data-position");
  $("#data_server_tab_position").val(last_position + 1);
  $("#data_server_tab_description").val("");
  $("#data_server_tab_server").val("");
  $("#data_server_tab_ip_internal").val("");
  $("#data_server_tab_priority").val("");
<% elsif !@result[:success] %>
  alert("<%= @result[:msg] %>");
<% end %>

app/views/variable_update/holiday_delete.js.erb
$("#holiday_new_record").val("true");
<% if @result[:success] %>
  $(".holiday_table .holiday_row[data-position='<%= @position%>']").first().remove();
  $(".holiday_table .holiday_row").each(function(ix,el){
    if( parseInt($(el).attr("data-position")) > <%= @position %> ){
      $(el).attr("data-position", parseInt($(el).attr("data-position")) - 1);
      $(el).find("td a").first().attr("href", "/tabs/holiday/"+$(el).attr("data-position").toString());
    }
  });
<% elsif !@result[:success] %>
  alert("<%= @result[:msg] %>");
<% end %>

app/views/variable_update/holiday_submit.js.erb
<% if @error %>
alert("An error occured while executing this operation");
<% elsif @new && @result[:success] %>
  $("#holiday_new_record").val("true");
  $(".holiday_table").append('<tr class="holiday_row" data-position="<%= @data["position"] %>" data-day="<%= @data["day"] %>" data-month="<%= @data["month"] %>" data-year="<%= @data["year"] %>" data-from="<%= @data["from"] %>" data-to="<%= @data["to"] %>"  data-symbol="<%= @data["symbol"] %>" data-description="<%= @data["description"] %>" data-enable="<%= @data["enable"] %>"><td class="el"><%= @data["year"]=="0" ? "****" : @data["year"] %>.<%= @data["month"] %>.<%= @data["day"] %></td><td class="el"><%= "#{@data["from"]["hour"].to_s.rjust(2, "0")}:#{@data["from"]["minute"].to_s.rjust(2, "0")}" %></td><td class="el"><%= "#{@data["to"]["hour"].to_s.rjust(2, "0")}:#{@data["to"]["minute"].to_s.rjust(2, "0")}" %></td><td class="el"><%= @data["symbol"] %></td><td class="el"><%= @data["description"] %></td><td><%= link_to "delete", delete_holiday_row_path(:position => @data["position"]), :remote=> true, :method => :delete %></td></tr>');
  $("#holiday_tab_position").val('<%= @data["position"].to_i + 1 %>');
  $("input[name='holiday_tab[enable]'][type='checkbox']").prop("checked", true);
  $("#holiday_tab_month").val("");
  $("#holiday_tab_day").val("");
  $("#holiday_tab_yearly_check").prop("checked", false);
  $("#holiday_tab_year").val("").show();
  $("#holiday_tab_from_hour").val("");
  $("#holiday_tab_from_minute").val("");
  $("#holiday_tab_to_hour").val("");
  $("#holiday_tab_to_minute").val("");
  $("#holiday_tab_comment").val("");
  $("#holiday_tab_symbol").val("");
  $("#holiday_tab_description").val("");
<% elsif @result[:success] %>
  $("#holiday_new_record").val("true");
  var row = $(".holiday_row[data-position='<%= @data['position']%>']")[0];
  $(row).attr("data-day", "<%= @data['day'] %>");
  $(row).attr("data-month", "<%= @data['month'] %>");
  $(row).attr("data-year", "<%= @data['year'] %>");
  $(row).attr("data-from", "<%= @data['from'] %>");
  $(row).attr("data-to", "<%= @data['to'] %>");
  $(row).attr("data-symbol", "<%= @data['symbol'] %>");
  $(row).attr("data-description", "<%= @data['description'] %>");
  $(row).attr("data-enable", "<%= @data['enable'] %>");
  $($(row).find("td")[0]).text("<%= @data['year']=='0' ? '****' : @data['year'] %>.<%= @data['month'] %>.<%= @data['day'] %>");
  $($(row).find("td")[1]).text("<%= @data['from']['hour'].to_s.rjust(2, '0') %>:<%= @data['from']['minute'].to_s.rjust(2, '0') %>");
  $($(row).find("td")[2]).text("<%= @data['to']['hour'].to_s.rjust(2, '0') %>:<%= @data['to']['minute'].to_s.rjust(2, '0') %>");
  $($(row).find("td")[3]).text("<%= @data['symbol'] %>");
  $($(row).find("td")[4]).text("<%= @data['description'] %>");
  var last_position = $(".holiday_table").find("tr").last().attr("data-position");
  $("#holiday_tab_position").val(last_position + 1);
  $("input[name='holiday_tab[enable]'][type='checkbox']").prop("checked", true);
  $("#holiday_tab_month").val("");
  $("#holiday_tab_day").val("");
  $("#holiday_tab_yearly_check").prop("checked", false);
  $("#holiday_tab_year").val("").show();
  $("#holiday_tab_from_hour").val("");
  $("#holiday_tab_from_minute").val("");
  $("#holiday_tab_to_hour").val("");
  $("#holiday_tab_to_minute").val("");
  $("#holiday_tab_comment").val("");
  $("#holiday_tab_symbol").val("");
  $("#holiday_tab_description").val("");
<% elsif !@result[:success] %>
  alert("<%= @result[:msg] %>");
<% end %>