config/routes.rb
MetaTrader::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :sessions => "users/sessions" }

  get "main_page", :to => "api_access#main_page", :as => "main_page"

  post "ping_session", :to => "api_access#ping_session", :as => "ping_session"

  post "tabs/common/submit", :to => "fixed_update#common_submit", :as => "common_submit"

  post "tabs/time/submit", :to => "fixed_update#time_submit", :as => "time_submit"

  post "tabs/backup/submit", :to => "fixed_update#backup_submit", :as => "backup_submit"

  post "tabs/symbol_group/submit", :to => "symbol#symbol_group_submit", :as => "symbol_group_submit"

  get "fetch_symbol", :to => "symbol#fetch_symbol", :as => "fetch_symbol"
  post "tabs/symbol/submit", :to => "symbol#symbol_submit", :as => "symbol_submit"
  get "new_symbol", :to => "symbol#new_symbol", :as => "new_symbol"

  get "fetch_group", :to => "group#fetch_group", :as => "fetch_group"
  post "tabs/group/submit", :to => "group#group_submit", :as => "group_submit"

  get "fetch_manager", :to => "manager#fetch_manager", :as => "fetch_manager"
  post "tabs/manager/submit", :to => "manager#manager_submit", :as => "manager_submit"

  get "fetch_feeder", :to => "feeder#fetch_feeder", :as => "fetch_feeder"
  post "tabs/feeder/submit", :to => "feeder#feeder_submit", :as => "feeder_submit"

  get "fetch_synchronization", :to => "synchronization#fetch_synchronization", :as => "fetch_synchronization"
  post "tabs/synchronization/submit", :to => "synchronization#synchronization_submit", :as => "synchronization_submit"

  get "fetch_plugin", :to => "plugin#fetch_plugin", :as => "fetch_plugin"
  post "tabs/plugin/submit", :to => "plugin#plugin_submit", :as => "plugin_submit"

  post "filter_account", :to => "account#filter_account", :as => "filter_account"
  get "fetch_account", :to => "account#fetch_account", :as => "fetch_account"
  post "tabs/account/submit", :to => "account#account_submit", :as => "account_submit"

  get "fetch_order", :to => "order#fetch_order", :as => "fetch_order"
  post "tabs/order/submit", :to => "order#order_submit", :as => "order_submit"

  post "tabs/access/submit", :to => "variable_update#access_submit", :as => "access_submit"
  delete "tabs/access/:position", :to => "variable_update#access_delete", :as => "delete_access_row"

  post "tabs/holiday/submit", :to => "variable_update#holiday_submit", :as => "holiday_submit"
  delete "tabs/holiday/:position", :to => "variable_update#holiday_delete", :as => "delete_holiday_row"

  post "tabs/data_server/submit", :to => "variable_update#data_server_submit", :as => "data_server_submit"
  delete "tabs/data_server/:position", :to => "variable_update#data_server_delete", :as => "delete_data_server_row"

  root :to => "api_access#main_page"

end

app/controllers/fixed_update_controller.rb
class FixedUpdateController < ApplicationController
  include ApplicationHelper

  def common_submit
    authorize! :update, :common
    data = params[:common_tab]
    api = ApiMethods.new
    begin
      result = api.updateCommon(data,session)
      if result[:success]
        render :nothing => true
      else
        @error = result[:msg]
        render "shared/error"  
      end
    rescue => e
      @error = "An error occured while executing this operation"
      render "shared/error"
    end
  end

  def time_submit
    authorize! :update, :time
    data = params[:time_tab].map { |k,v| v.to_i }
    api = ApiMethods.new
    begin
      result = api.updateTime(data,session)
      if result[:success]
        render :nothing => true
      else
        @error = result[:msg]
        render "shared/error"  
      end
    rescue => e
      @error = "An error occured while executing this operation"
      render "shared/error"
    end
  end

  def backup_submit
    authorize! :update, :backup
    data = params[:backup_tab]
    api = ApiMethods.new
    begin
      result = api.updateBackup(data,session)
      if result[:success]
        render :nothing => true
      else
        @error = result[:msg]
        render "shared/error"  
      end
    rescue => e
      @error = "An error occured while executing this operation"
      render "shared/error"
    end
  end

end

app/views/fixed_update/_backup_form.html.erb
<% unless @backup.nil? %>
  <%= @backup %>

    <h1>400 &mdash; Bad Request</h1>
    <p>Not enough data{"method":"CfgUpdateBackup","update":[{"field":"watch_ip","value":0},{"field":"watch_role","value":0},{"field":"watch_password","value":0},{"field":"watch_opposite","value":0},{"field":"fullbackup_path","value":"C:\\MetaTrader4Backup"},{"field":"fullbackup_period","value":1},{"field":"fullbackup_shift","value":0},{"field":"archive_period","value":4},{"field":"archive_shift","value":0},{"field":"archive_store","value":0},{"field":"external_path","value":""},{"field":"export_securities","value":""},{"field":"export_period","value":4},{"field":"export_path","value":""}]}</p>


  <%= form_tag backup_submit_path, :method => "POST", :remote => true do %>
    <%= submit_tag %>
    <%= hidden_field_tag "backup_tab[watch_ip]", @backup["backup_tab"] %>
    <table>
      <tr>
        <th>Property</th>
        <th>Value</th>
      </tr>
      <tr>
        <td>Server role</td>
        <td><%= select_tag "backup_tab[watch_role]", options_for_watch_role(@backup["watch_role"])%></td>
      </tr>
      <tr>
        <td>Password of the slave server</td>
        <td><%= password_field_tag "backup_tab[watch_password]", @backup["watch_password"].encode('utf-8', 'iso-8859-1'), :readonly => @backup["watch_role"]==0 %></td>
      </tr>
      <tr>
        <td style="width: 250px;" >Oposite server IP address and port</td>
        <td><%= text_field_tag "backup_tab[watch_opposite]", @backup["watch_opposite"], :readonly => @backup["watch_role"]==0 %></td>
      </tr>
      <tr>
        <td>Full backup to</td>
        <td><%= text_field_tag "backup_tab[fullbackup_path]", @backup["fullbackup_path"], :style => "width: 300px;"%></td>
      </tr>
      <tr>
        <td>Full backup every</td>
        <td>
          <%= select_tag "backup_tab[fullbackup_period]", options_for_backup_period(@backup["fullbackup_period"])%>
          <span style="color: lightgray;"><%= Time.zone.at @backup["fullbackup_lasttime"] %></span>
        </td>
      </tr>
      <tr>
        <td>Full backup time</td>
        <td>
          <% time = @backup["fullbackup_shift"] %>
          <%= number_field_tag "backup_tab[fullbackup_shift][hour]", (time/60).to_i %>:<%= number_field_tag "backup_tab[fullbackup_shift][minute]", time.to_i - (time/60).to_i*60 %>
        </td>
      </tr>
      <tr>
        <td>Archival backup every</td>
        <td>
          <%= select_tag "backup_tab[archive_period]", options_for_arch_backup_period(@backup["archive_period"])%>
          <span style="color: lightgray;"><%= Time.zone.at @backup["archive_lasttime"] %></span>
        </td>
      </tr>
      <tr>
        <td>Shift of archive backup time</td>
        <td><%= number_field_tag "backup_tab[archive_shift]", @backup["archive_shift"] %> minute(s)</td>
      </tr>
      <tr>
        <td>Keep archival backups within</td>
        <td><%= select_tag "backup_tab[archive_store]", options_for_archive_store(@backup["archive_store"])%></td>
      </tr>
      <tr>
        <td>Archival backup external processing</td>
        <td><%= text_field_tag "backup_tab[external_path]", @backup["external_path"], :style => "width: 300px;" %></td>
      </tr>
      <tr>
        <td>Export symbols</td>
        <td><%=text_field_tag "backup_tab[export_securities]",@backup["export_securities"],:style=>"width: 300px;"%></td>
      </tr>
      <tr>
        <td>Export external processing every</td>
        <td><%= select_tag "backup_tab[export_period]", options_for_export_period(@backup["export_period"])%></td>
      </tr>
      <tr>
        <td>Export external processing</td>
        <td><%= text_field_tag "backup_tab[export_path]", @backup["export_path"], :style => "width: 300px;" %></td>
      </tr>
    </table>
  <% end %>
<% end %>

app/views/fixed_update/_common_form.html.erb
<% unless @common.nil? %>
  <%= form_tag common_submit_path, :method => "POST", :remote => true do %>
    <%= submit_tag %>
    <table style="margin: 10px">
      <tbody>
        <tr>
          <td>Server</td>
          <td><%= @common["owner"] %></td>
        </tr>
        <tr>
          <td>Name</td>
          <td><%= text_field_tag "common_tab[name]", @common["name"] %></td>
        </tr>
        <tr>
          <td>IP Address</td>
          <td><%= select_tag "common_tab[address]", options_for_ip_address(@common["bind_adresses"],@common["address"]) %></td>
        </tr>
        <tr>
          <td>Communication port</td>
          <td><%= text_field_tag "common_tab[port]", @common["port"] %></td>
        </tr>
        <tr>
          <td>Demo accounts</td>
          <td><%= select_tag "common_tab[typeofdemo]", options_for_demo_type(@common["typeofdemo"]) %></td>
        </tr>
        <tr>
          <td>Time of demo</td>
          <td><%= number_field_tag "common_tab[timeofdemo]", @common["timeofdemo"] %> days</td>
        </tr>

        <tr>
          <td>Time zone</td>
          <td><%= select_tag "common_tab[timezone]", options_for_timezone(@common["timezone"]) %></td>
        </tr>
        <tr>
          <td>Daylight Saving Time correction</td>
          <td><%= select_tag "common_tab[daylightcorrection]", options_for_yes_no(@common["daylightcorrection"]) %></td>
        </tr>
        <tr>
          <td>End of day time</td>
          <td><%= number_field_tag "common_tab[endhour]", @common["endhour"] %>:<%= number_field_tag "common_tab[endminute]", @common["endminute"] %></td>
        </tr>
        <tr>
          <td>Rollover mode</td>
          <td><%= select_tag "common_tab[rollovers_mode]", options_for_rollover(@common["rollovers_mode"]) %></td>
        </tr>
        <tr>
          <td>Statements mode</td>
          <td><%= select_tag "common_tab[statement_mode]", options_for_statements(@common["statement_mode"]) %></td>
        </tr>
        <tr>
          <td>Monthly statements mode</td>
          <td><%= select_tag "common_tab[monthly_state_mode]", options_for_monthly_statements(@common["monthly_state_mode"]) %></td>
        </tr>
        <tr>
          <td>Generate statements at weekends</td>
          <td><%= select_tag "common_tab[statement_weekend]", options_for_yes_no(@common["statement_weekend"])%></td>
        </tr>
        <tr>
          <td>Keep internal emails</td>
          <td><%= number_field_tag "common_tab[keepemails]", @common["keepemails"] %> days</td>
        </tr>
        <tr>
          <td>Keep ticks</td>
          <td><%= number_field_tag "common_tab[keepticks]", @common["keepticks"] %> days</td>
        </tr>
        <tr>
          <td>Optimization time</td>
          <td><%= number_field_tag "common_tab[optimization_t][optimization_time_h]", time_hours(@common["optimization_time"]) %>:<%= number_field_tag "common_tab[optimization_t][optimization_time_m]", time_minutes(@common["optimization_time"]) %></td>
        </tr>
        <tr>
          <td>Antiflood controlls</td>
          <td><%= select_tag "common_tab[antiflood]", options_for_yes_no(@common["antiflood"]) %></td>
        </tr>
        <tr>
          <td>Antiflood max. connections</td>
          <td><%= number_field_tag "common_tab[floodcontrol]", @common["floodcontrol"] %></td>
        </tr>
        <tr>
          <td>Feeder switch timeout</td>
          <td><%= number_field_tag "common_tab[feeder_timeout]", @common["feeder_timeout"] %> seconds</td>
        </tr>
        <tr>
          <td>Live update mode</td>
          <td><%= select_tag "common_tab[liveupdate_mode]", options_for_live_update(@common["liveupdate_mode"]) %></td>
        </tr>
        <tr>
          <td>Time synchronization with</td>
          <td><%= select_tag "common_tab[timesync]", options_for_timesync(@common["timesync"]) %></td>
        </tr>
        <tr>
          <td>IP Access list of web services</td>
          <td>
            <% @common["web_adresses"].each_with_index do |wa, ix| %>
              <%= text_field_tag "common_tab[web_adresses][#{ix}]", ApiMethods.long2ip(wa), :style => "width: 120px;" %>
              <% if ix==3 %><br/><% end %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Path to accounts/orders bases</td>
          <td><%= text_field_tag "common_tab[path_database]", @common["path_database"], :style => "width: 300px;" %></td>
        </tr>
        <tr>
          <td>Path to history bases</td>
          <td><%= text_field_tag "common_tab[path_history]", @common["path_history"], :style => "width: 300px;" %></td>
        </tr>
        <tr>
          <td>Path to log files</td>
          <td><%= text_field_tag "common_tab[path_log]", @common["path_log"], :style => "width: 300px;" %></td>
        </tr>
        <tr>
          <td>Adapters</td>
          <td>
            <%= select_tag "common_tab[adapter][selected_adapter]", options_for_adapters(@common["adapters"].split('|')) %>
            <%= hidden_field_tag "common_tab[adapter][full_adapter_list]", @common["adapters"] %>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% end %>

app/views/fixed_update/_time_form.html.erb
<% if @time %>
  <% days = @time["days"] %>
  <%= form_tag time_submit_path, :method => "POST", :remote => true do %>
    <table>
      <tr>
        <th></th>
        <% (0..23).to_a.each do |hour| %>
          <th><%= hour.to_s.rjust(2, '0') %></th>
        <% end %>
        <th>*</th>
      </tr>
    <% (0..6).to_a.each do |day| %>
      <tr>
        <td><%= day_of_week(day) %></td>
      <% days[(day*24)+0..(day*24)+23].each_with_index do |hour, ix| %>
        <td class="time_check">
          <input name="<%= "time_tab[#{(day*24) + ix}]" %>" type="hidden" value="0" />
          <%= check_box_tag "time_tab[#{(day*24) + ix}]", '1', days[(day*24) + ix] == 1 %>
        </td>
      <% end %>
        <td>
          <%= link_to "*", "#", :class => "time_switch" %>
        </td>
      </tr>
    <% end %>
    </table>
    <%= submit_tag %>
  <% end %>
<% end %>